{% set name = "paintera-conversion-helper" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 34707550ec936901561f284d03545bd30543c5f18dd4ba029943282ab92581cc

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . -vvv"
  noarch: python
  entry_points:
    - paintera-conversion-helper=paintera_conversion_helper:launch_pch
    - extract-to-scalar=paintera_conversion_helper:launch_extract_to_scalar

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - jgo >=0.4.0

test:
  imports:
    - paintera_conversion_helper

about:
  home: https://github.com/saalfeldlab/paintera-conversion-helper-cmd
  license: GPL2
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'Python command line launcher for Paintera Conversion Helper'
  doc_url: https://github.com/saalfeldlab/paintera-conversion-helper-cmd
  dev_url: https://github.com/saalfeldlab/paintera-conversion-helper-cmd

extra:
  recipe-maintainers:
    - hanslovsky
    - igorpisarev
    - axtimwalde
