travis:
  secure:
    BINSTAR_TOKEN: UVsFUcKdFekGMr4LNp+x2ErPraX3QwsTBlOHNci0CyifxsDItQ/WaM0nfebBbf8dmEmKYq4xz5TZenZmDlEk9TuRXJ5Jr5g+6iJBVHSrXsWFkEWgA7EJfqxNhllmmQJ3SR0jsnM+eCEMOx8zmb7LQU938ya/BJHD1/wiEiOzB/JxCWctLhg7IO421VgWPkpzzM4j3KVGg5PdcegQls+jfOmBf5te3xxL1e060rrVWdfBr9muFWVZKwRHJqmKh5GWfQGS3znLXmPGUYG09n0Cpdn8GnwsivmXiQ75dhtDmE2k/ho6AeB086IENU4RBXtpS/qeEWvpNbJHY9cgbIKCupcK955GOVlRstm5ZBQaoXkrWmfV9UDZR+NsDKOID8WvBVg6AIszzmz3t8ioTApy5JlGCnbd5859IoRAiuwx96dANxoEWrAzkwFlIXzjwfSaRQbqSMYs1Y9y4jA/c+xHjDVKsPWz9ZvcYG8/YCiYk8m/641bGy3Lg78bTSWmkCwk/kTibGC1+BgXxmgALdwf+t0K9YKEiJpOG5hMDCI3AFrQEw0Po6yAR/3rzmhdeAAYxnMFdkYiAFRvgegWUESOEcVgD9GEM+V5DNVQFd/9E6lf8G4gZ3yYylZiA3oHDsgOrjqpG+KSOEerE55RrXE0tK7cuD1ny2Nmp9WEAIekM0o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
