travis:
  secure:
    BINSTAR_TOKEN: bi+mRKncJNyeKA431kyIhXufqqxWYgRDvk9UxwFn0EHU6u3CXI2hFNlHzC05MlOucphKe/rfT6woWSJ7UX5d07KjbscBH15VJNsP8R2q8OlBQ/nMYe2f/OFf6UrlYJIQ/xFKrstknff+yGyf8AzjBrOHeetcCbmcqXJMkfJc388vFCoqZFvWe7r7V3sFb1HaoEQpjp7p1Ybms4WgCq7wPIPlswQj6vre3torjMflLneq4yw2fCeh0cOrKqnlJbjbdA0tQASCXxmTCg+PltN8ri03x0r8s5dGz/ImO80Yw94Xg0k8X3bCt16sX2GzZ3dLp2hQ/FZZ2Ib0duMsaa6HjGNqNMLc/lKLEON7r5dat3cqwYKF7+FaxEzXOSm+Y7NxQicfsWv0PRG9wjlDxf9VvMupz4V2mxM8siSBIZEl21HJnGhMdihRHP2yPNFZ8Wf52K7R1Nih65oM37jqR9HBa5rLbwkK9L8e25PI27M4KpyQD/ldbV5ZX9XKBUKA4IPibdZt+CCnL2thYTzf5+ZLu4dA7jEHDFupRt7BZO5Xshu87rbArsYVKLaRkln/t1ceLnWHknCs00x3GQqgQoEhmjze8FeGExU5FYLBlP28nT57RbQr7LkcSNFQ7NKoQWXOJOXDUUkg6PCkCk8cGt6ge/eGI5j/cED895bETGsB0VE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
