travis:
  secure:
    BINSTAR_TOKEN: XGuZ/iZ8Ke4NSqK3cbxvqCJpUxuVPORx7dMmU6aK5pn90R4oRz10q5BoHiLWyitnMQYFHRCzhYl4FYD5jpg1o4LFlU9v/iEiV7dJhODmnsrYIgCtN/dB8jDzrdmmN7tOta1yZQ+cg0yJpIjtYktRLmIBe6xvS89fWwyYnvglAc0tUI4CBlOfC+abckVXuqL/mh5KJW8xdiG4Z8jww2F+DpKcuokDu4ogFVdQ5CGhHBXjlHz3UTnPt+S5/FmTgWB2ugdTC0/8LwcMTVgMC2eJxULtDZDfk5D4qQ0tLzj2CLfbniNNgztF1eQLex8TXhVDRCNyqCBZAD89Bgg2tYIIbfjZt2q7Pcgjko2yVPUfvFOqQbrlCVkBe8Fee4HcbVLD749XpSIDeye0OhtLPTfC8ZcHysCGlKXsD4KsOVzf0DQa6emqfroEU1jW33fzuqZL01WELfTsLv1aAzZm3Fm2HW4AhjlXvxGNPxSHyFX/UujkhBo5cwqvgUB7bbin3V4Jpz0UqLJJPa9WvSGq4dmcx2YbeJt+38cuR+5lgoou2JAIGdya3KdMyoHuGBiTSSu6nZJz6UHtjZD/pQ7SxTwtv07ZsHwd84N1ieyNZ1/aC0zsejNxtVq2v2UOP9CLaSom7dNaR+GEKIF5SPhh+NWp8zx0OP1XMfaSB1ndpLISwNM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
