travis:
  secure:
    BINSTAR_TOKEN: KkME0hECaCknCBLw2Bvz8YW05zx2AbvA1HHdK+BS8q8Dw/vE+JlhU2yb7nqqsrtfh8UkmKK30FKNPCc0DuiDM9Sc2B9He2+17ydToug8gNLV4xSALCuxYwENe8NVkv/lEZuVsq/nyHrPycaOygubNSg+GbO0rciYTAQKCMv6I7U761yIzl+HJHRYbXWtUsZcCwfE4qNmA9FEFAZH0o1v2eUS7jHnYbFbzUmzi7ruCv4UtHJhECv805LdVxvsGVvQiQffB7nxiMZsYo8iaFu+xr73gh92SRC5odFRzHZk84Vn82ASJ9bzV9CfLqFHaP7dSRq0RPn8HWgYdoVNQAcwkJ2OYLB5/yTb29j1rry0cWTYJAIQYoQDFUM/axJ+Wa2xkubLz9cdtaLtdCgjxCWXXSxNk7k5HK4GO2VOyxKsT5XX95X7X8Fr17rROJRW1o8bKW445S674Z626cCk+YA1a3dl44q2x05WdaT1P0txjYg6PZY3Keo8RFe5SUF1mW0ou9o+aISve+wIfhoL8gdXAPfINeYcgW2ERBGqqiiRuL1VcmigHb+4M8uL2EMi22T/qb8ooxui+ObA3cD2NkL1yOTO+yLdbJ+Ejs3z9xYrHWRpLvh2gXkcv2OXuWEkzRjrwL9ajc8uVA7oO6orGXizTQhe6McLmiv+ML0G/+wbTaU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
