travis:
  secure:
    BINSTAR_TOKEN: 3zwvsnDwvDjkCqd0kiVX0dvGQo0Or4jA800YwtgaY+sryRcruP/Y01kZViWOQ8xfht03QeuQOb/QtnREoZ3L8SMGdBx/TrelXwZrZcNht4JCIwpHPgmZwT6aMykP8NpjEqYFeLC1NFXtHt9J0E4QcyMoK5p9XD6iYoMfCjjMaDsF5X+9mxzjJumJadxdguMWGUyfwyZe6+bYkecaKjHsrDYek5zFSiosZKCNIljdqwZxoY+NEXwsagk+u2ydHDNsA1Tj0gOdsu12MgszxNxaRjO4/3TsTBEA7utdl8HbytI5/fy30GU3xeVNzFnqueEekeHzgxDd1x5XklUNJWrocHRB75z5DnmWbYe612VKktS4Vm30bCgJ28eO89yfJJJe01dVX2uZilgDRpzmLZ2vvkzoqwR5xocp38tSfOHF3jFNMoTcpT5cmuBimYvAKpMGjqSN7ZfzffIy45AjcxHK3hACPjA2Lli+TZucJn9r3CAJlY8WWUCZsD+pyiuVh1v6EM4ejTEo+EE29sWmQqyN0HJ1ZV7DT0f7JvAztUwIn7ETvXQDTf7a9KHbNN/WX0/pTfMMBnB0wO7gbRHtdAqlwt61GkOGt8Qh1syD8C94QRH4yeanzNnNtmRPwaeF32AVayHqG+qe7EM+8WvwoqAoZDvWzhtbUTlJV4Mcl4Lb8xk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
