travis:
  secure:
    BINSTAR_TOKEN: nfKRYshLFDRAl4Nuj+L+c2+KrGaXUhm2++n8ykZhpiBEKUbileXYCWPavS8+MC0yczvfGdecgjtXn6+MnE6klZR793QYNEN+GsafJvAD+hysTz97yzmTr6gkeg7uzeR+xLKdhqfSpGT7TP2yawCwdi3IXzrrHiRZGXYVRNgqoWV+esxJpA56Lfyp1kp4tI3PfDBSmeNpAtVZmjC3tgBveB5UJy9YM7pyvlZPFA3vhBojvtIvHy6s50Hg7A0c4O7ZvuVZTKH5ZbfSj1y33WdaH/gEZ0i6DTJUFHWEbeHxTCC5tSF43iRlNztespkiaXsO7xvAQ+E6/5v/YUSXR7U9bCmUYqkUk38UhQUG2XaT/Sxi8y871Ch5Lkk9n9Dmk/CMj+y1DiU027zmCHzNprF5QsKRrgNo+fXOlpIxv0+UmPIty/dfPICBGz2CWXVWFHLa+HaV2skqjEgsikyntJ9u0JgXKmkWvrNqFtGjCrvmxRsuVSJbIVFKN2db+tJ4Gm3L7gGmHxju5agTGWPYktRihFcWdX/8B/MHEhxNo69pXsFmuKq6rE/layGysVGC6nSAsJS5NE06gqRb9WK0I1NKwKxkFhEsN07SafGrYEaEWg0KLcZNzuqr0gQPKZHSMJvP1+4E32i5jtrEhCSposjhNYvqs+CuGxjjwARPjgLrr/k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
